---
- name: init
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: init
      tags: init

- name: homebrew
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: homebrew
      tags: homebrew
