---
- name: init
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: init
      tags: init

- name: homebrew
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: homebrew
      tags: homebrew

- name: native
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: native
      tags: native

- name: osx
  hosts: localhost
  connection: local
  gather_facts: yes
  handlers:
    - name: "Restart Dock"
      shell: "killall Dock"
    - name: "Restart Finder"
      shell: "killall Finder"
    - name: "Restart Safari"
      shell: "killall Safari && open /Applications/Safari.app/"
  roles:
    - role: osx
      tags: osx
