---

- name: Show dotfiles
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: string
    value: true
  notify: Restart Finder

- name: Hide recent items
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: int
    value: 0
  notify: Restart Dock

- name: Disable writing network store .DS_Store
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: string
    value: true
  notify: Restart Finder

- name: Show battery status
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: yes

- name: Show path bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  notify: Restart Finder

- name: Avoid opening mission control
  osx_defaults:
    domain: com.apple.spaces
    key: spans-displays
    type: bool
    value: true
