---
- name: Setup global .gitignore
  shell: git config --global core.excludesfile $HOME/.gitignore

- name: Show Japanese properly
  shell: git config --global core.quotepath false

- name: Set pull rule
  shell: git config --global pull.rebase true

- name: Set git user
  shell: |
    git config --global user.email 'rikuson@users.noreply.github.com'
    git config --global user.name 'Rikson'

- name: Use homebrew based git
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: git }
