---
- name: Tap brew packages
  homebrew_tap:
    name: "{{ item.name }}"
  with_items:
    - { name: "jesseduffield/lazygit" }

- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: "jesseduffield/lazygit/lazygit" }

