---
- name: Tap brew packages
  homebrew_tap:
    name: "{{ item.name }}"
  with_items:
    - { name: universal-ctags/universal-ctags }

- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
  with_items:
    - { name: vim }
    - { name: universal-ctags }

- name: Install vim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: $HOME/.vim/autoload/plug.vim
