name: Check init

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  homebrew:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Cache gem
      uses: actions/cache@v3
      with:
        path: /Library/Ruby/Gems
        key: ${{ runner.os }}-gem-${{ hashFiles('provision/roles/init/tasks/*.yml') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Cache homebrew
      uses: actions/cache@v3
      with:
        path: /opt/homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('provision/roles/homebrew/tasks/*.yml') }}
        restore-keys: ${{ runner.os }}-homebrew-
    - name: Install ansible
      run: brew install ansible
    - name: Play init tasks
      run: ansible-playbook playbook.yml -i hosts --tags=init
      working-directory: provision
    - name: Check init spec
      run: rake serverspec:init
      working-directory: provision
    - name: Copy dotfiles
      run: |
        cp -r .vim $HOME/
        cp .vimrc $HOME/
        cp -r .gnupg $HOME/
    - name: Play homebrew tasks
      run: ansible-playbook playbook.yml -i hosts --tags=homebrew
      working-directory: provision
    - name: Check homebrew spec
      run: rake serverspec:homebrew
      working-directory: provision
